# Generated by Django 2.2.6 on 2019-10-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_remove_dates_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
