# Generated by Django 2.2.6 on 2019-10-11 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0005_auto_20191011_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
