# Generated by Django 2.2.6 on 2019-10-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0006_auto_20191011_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='descr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
