# Generated by Django 2.2.6 on 2019-10-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0007_dates_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='type',
            field=models.CharField(default='', max_length=24),
        ),
    ]
