# Generated by Django 2.2.6 on 2019-10-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0008_dates_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='type',
            field=models.CharField(default=None, max_length=24),
        ),
    ]
